(global-set-key (kbd "<f12> a") 'org-agenda)
(global-set-key (kbd "<f12> b") 'org-iswitchb)
(global-set-key (kbd "<f12> l") 'org-store-link)
(global-set-key (kbd "<f12> c") 'org-capture)
(global-set-key (kbd "<f12> t") 'org-clock-goto)

(add-hook 'org-mode-hook (lambda()
                           (define-key org-mode-map (kbd "M-n") 'org-forward-paragraph)
                           (define-key org-mode-map (kbd "M-p") 'org-backward-paragraph)))


;; (global-set-key (kbd "C-c c") 'org-capture)
;;
;; (add-hook 'org-mode-hook (lambda()
;;                            (define-key org-mode-map (kbd "<f11>") 'org-clock-goto)
;;                            (define-key org-mode-map (kbd "C-c b") 'org-iswitchb)
;;                            (define-key org-mode-map (kbd "<S-f5>") 'bh/widen)
;;                            (define-key org-mode-map (kbd "<f9> <f9>") 'bh/show-org-agenda)
;;                            (define-key org-mode-map (kbd "<f9> b") 'bbdb)
;;                            (define-key org-mode-map (kbd "<f9> c") 'calendar)
;;                            (define-key org-mode-map (kbd "<f9> f") 'boxquote-insert-file)
;;                            (define-key org-mode-map (kbd "<f9> g") 'gnus)
;;                            (define-key org-mode-map (kbd "<f9> h") 'bh/hide-other)
;;                            (define-key org-mode-map (kbd "<f9> n") 'bh/toggle-next-task-display)
;;                            (define-key org-mode-map (kbd "<f9> w") 'widen)
;;                            (define-key org-mode-map (kbd "<f9> u") 'bh/narrow-up-one-level)
;;                            (define-key org-mode-map (kbd "<f9> I") 'bh/punch-in)
;;                            (define-key org-mode-map (kbd "<f9> O") 'bh/punch-out)
;;                            (define-key org-mode-map (kbd "<f9> o") 'bh/make-org-scratch)
;;                            (define-key org-mode-map (kbd "<f9> r") 'boxquote-region)
;;                            (define-key org-mode-map (kbd "<f9> v") 'visible-mode)
;;                            (define-key org-mode-map (kbd "<f9> SPC") 'bh/clock-in-last-task)
;;                            (define-key org-mode-map (kbd "M-<f9>") 'org-toggle-inline-images)
;;                            (define-key org-mode-map (kbd "C-x n r") 'narrow-to-region)))

;; (add-hook 'org-agenda-mode-hook (lambda()
;;                                   (define-key org-agenda-mode-map (kbd "<f9> I") 'bh/punch-in)
;;                                   (define-key org-agenda-mode-map (kbd "<f9> O") 'bh/punch-out)))
